services:
  postgres:
    container_name: newscentr-postgres
    image: postgres:16.3
    restart: always
    environment:
      - PGUSER=${PGUSER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "${DOCKER_PG_PORT}:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=256"
      - "-c"
      - "shared_buffers=4GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "work_mem=4GB"
      - "-c"
      - "maintenance_work_mem=4GB"

  migrate:
    container_name: newscentr-migrate
    environment:
      - PRISMA_URL=${PRISMA_URL}
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    command: yarn prisma:deploy

  prisma:
    container_name: newscentr-prisma-studio
    environment:
      - PRISMA_URL=${PRISMA_URL}
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    command: yarn prisma:studio
    ports:
      - "${DOCKER_PRISMA_PORT}:5555"

  server:
    container_name: newscentr-server
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: yarn server:start
    ports:
      - "${DOCKER_SERVER_PORT}:4444"

volumes:
  pg: null
  pgadmin-data: null