/*
  Warnings:

  - You are about to drop the `Translation` table. If the table is not empty, all the data it contains will be lost.

*/
-- AlterTable
ALTER TABLE "Ingredient" ALTER COLUMN "previewAlt" SET DATA TYPE TEXT,
ALTER COLUMN "previewTitle" SET DATA TYPE TEXT,
ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "pageName" SET DATA TYPE TEXT,
ALTER COLUMN "pageTitle" SET DATA TYPE TEXT,
ALTER COLUMN "text" SET DATA TYPE TEXT,
ALTER COLUMN "keywords" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT,
ALTER COLUMN "previewAlt" SET DATA TYPE TEXT,
ALTER COLUMN "previewTitle" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "PostCategory" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "keywords" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT,
ALTER COLUMN "text" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Recipe" ALTER COLUMN "pageName" SET DATA TYPE TEXT,
ALTER COLUMN "pageTitle" SET DATA TYPE TEXT,
ALTER COLUMN "text" SET DATA TYPE TEXT,
ALTER COLUMN "keywords" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT,
ALTER COLUMN "previewAlt" SET DATA TYPE TEXT,
ALTER COLUMN "previewTitle" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "RecipeCategory" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "keywords" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT,
ALTER COLUMN "text" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "RecipeIngredient" ALTER COLUMN "value" SET DATA TYPE TEXT,
ALTER COLUMN "note" SET DATA TYPE TEXT;

-- DropTable
DROP TABLE "Translation";
